name: Build and Deploy 

on:
  push:
    branches:
      - main

env:
  NODE_ENV: production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        npm ci

    - name: Build the application
      run: |
        npm run build

    - name: Push build to deployment branch
      uses: ad-m/github-push-action@v0.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: deployment
        force: true
